
ci:
  skip: ["docs"]
  autofix_prs: false
default_language_version:
  python: "python3"
fail_fast: true

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.6.0"
    hooks:
      - id: "check-added-large-files"
        exclude: "tests/cassettes/.*"
      - id: "check-ast"
      - id: "check-byte-order-marker"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "check-merge-conflict"
      - id: "check-vcs-permalinks"
      - id: "check-xml"
      - id: "check-yaml"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
        exclude: ".+\\.ipynb"
      - id: "name-tests-test"
      - id: "trailing-whitespace"

  - repo: "https://github.com/psf/black"
    rev: "24.4.2"
    hooks:
      - id: "black"

  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    # Ruff version.
    rev: 'v0.4.5'
    hooks:
      - id: "ruff"

  - repo: "https://github.com/python-poetry/poetry"
    rev: "1.7.1"
    hooks:
      - id: "poetry-check"
      - id: "poetry-lock"
        args: ["--check"]
      - id: "poetry-export"
        name: 'poetry export main'
        args: [ "--without-hashes", "--only", "main", "-f", "requirements.txt", "-o", "requirements/requirements.txt" ]

  - repo: "local"
    hooks:

      - id: "mypy"
        name: "mypy"
        entry: "make mypy"
        language: "system"
        types: ["python"]

      - id: "docs"
        name: "docs"
        entry: "make docs"
        language: "system"


