[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

# default theme
[theme]
base="dark"
#primaryColor="#F63366"

backgroundColor="#000000"  # Black

#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"

## Primary accent for interactive elements
#primaryColor = '#7792E3'

## Background color for the main content area
#backgroundColor = '#152630'

## Background color for sidebar and most interactive widgets
#secondaryBackgroundColor = '#bfbfbf'

## Color used for almost all text
#textColor = '#0693e3'

## Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
font = "sans serif"
