name: test

on:
  push:
    branches:
      - main

    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/*test*.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements/requirements*.txt"

jobs:
  test:
    name: test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11"]
        include:
          - os: "macos-latest"
            python: "3.10"
          - os: "macos-latest"
            python: "3.11"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@main
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements/*') }}
      - run: pip install -r requirements/requirements.txt
      - run: python --version
      - run: python -m pip --version
      - run: pytest --version
      - run: python -m pip cache info
      - run: black --check src
      - run: isort --check-only src
      - run: ruff --check src
      - run: mypy src
      - run: pytest --cov=src tests
      - run: pyright src